.TH hasciicam 1 "July 16, 2001" "hasciicam"
.SH NAME
hasciicam \- (h)ascii for the masses!
.SH SYNOPSIS
.B hasciicam
[ \fB-hvq\fR ]
[ \fB-m \fImode\fR ]
[ \fB-d \fIdevice\fR ]
[ \fB-i \fIinput\fR ]
[ \fB-n \fInorm\fR ]
[ \fB-s \fIsize\fR ]
[ \fB-o \fIoutput\fR ]
[ \fB-f \fIuser@ftp.foo.org:/dir\fR ]
[ \fBrendering\-options\fR ]
.SH DESCRIPTION
.B hasciicam
makes it possible to have live asciivideo on the web. It takes video from a capture device (like tv cards or quickcams) and renders it into ascii, formatting the output into an \fBhtml page\fP with a refresh tag or in a \fBlive ascii\fP window or in a simple \fBtext file\fP as well, giving the possiblity to publish on the web a live asciivideo feed browsable without any need for browser's plugins.

.B hasciicam
grabs frames using \fBVideo4Linux\fP api, renders them into ascii using \fBAA-lib\fP engine and is capable of armoring them with auto-refreshing
.SM HTML
code. It's being used also \fBjpeglib\fP for optionally refresh a small jpeg image, so that it can work also as a simple webcam (or showing both, jpeg and asciivideo).
.SH OPTIONS
.B
.IP "-h --help"
Display a help text and quit.
.B
.IP "-v --version"
Display version and quit.
.B
.IP "-q --quiet"
Be quiet and don't show hardware detection.
.B
.IP "-m --mode"
Selects the mode in wich hasciicam will run:
.br
.B live\fP will use the console (or eventually open one under X display) to show full speed ascii video.
.br
.B html\fP will write html formatted ascii video every \fIrefresh\fP seconds into file \fIaafile\fP.
.br
.B text\fP will write plain text  ascii video every \fIrefresh\fP seconds into file \fIaafile\fP.
.br
Default mode is \fBlive\fP. Mode selection is XOR'ed.
.B
.IP "-d --device"
Use specified capture device. Default is \fB/dev/video\fP.
.B
.IP "-i --input"
Selects the \fBdevice\fP's input channel to be used for grabbing frames. Default is \fB1\fP.
.B
.IP "-n --norm"
Selects video format to be used on tuner: \fBpal\fP | \fBntsc\fP | \fBsecam\fP | \fBauto\fP. Default is \fBauto\fP.
.B
.IP "-s --size"
Sets rendered ascii frames size to \fBWxH\fP characters. Grabbed frame size is computed from this value, resulting into (W<<1)x(H<<1). Default is \fB96x72\fP, or the minimum grabbing size supported by the device if greater.
.B
.IP "-o --aafile"
Defines the file where to save rendered ascii, overwrited every \fIrefresh\fP seconds. Default is \fBhasciicam.html\fP when in \fBhtml\fP mode, \fBhasciicam.txt\fP when in \fBtext\fP mode (unuseful when in \fBlive\fP mode).
.B
.IP "-f --ftp"
Ftp pushes the selected output file to an ftp account specified within an expression like \fBuser@dyne.org:/home/user/www\fP, hasciicam asks then for the account password on stdin (hidden while typing). Remote file is refreshed depending on \fBrefresh\fP rate and connection bandwidth, a \fIscolopendro\fP temporary file is created to keep clients on the other side refreshing smooth.
.B
.IP "-D --daemon"
Forks to background and runs in daemon mode.

.SH RENDERING-OPTIONS
.B
.IP "-S --font-size"
Selects a font size from \fB1\fP to \fB4\fP used in html rendering. default is \fB1\fP (only useful when in \fBhtml\fP mode).
.B
.IP "-a --font-face"
Selects a font face to be used in html rendering, it should be fixed size for better results. default is \fBcourier\fP (only useful when in \fBhtml\fP mode).
.B
.IP "-r --refresh"
Specifies the refresh interval in seconds between each grabbed frame. Default is \fB2\fP (unuseful when in \fBlive\fP mode).
.B
.IP "-b --aabright"
Specifies brightness level for the aa_render, from 0 to 100. Default is \fB50\fP.
.B
.IP "-c --aacontrast"
Specifies contrast level for the aa_render, from 0 to 100. Default is \fB10\fP.
.B
.IP "-g --aagamma"
Specifies gamma correction level for the aa_render, from 0 to 100. Default is \fB10\fP.
.B
.IP "-I --invert"
Invert and render the resulting negative ascii.
.B
.IP "-B --background"
Specifies the background color to be used in the form of a \fIhex RGB triplet\fR (without the leading #). Default is \fB000000\fP for black (only useful when in \fBhtml\fP mode).
.B
.IP "-F --foreground"
Specifies the foreground color to be used in the form of a \fIhex RGB triplet\fR (without the leading #). Default is \fB00FF00\fP for green (only useful when in \fBhtml\fP mode).
.B
.IP "-O --jpgfile"
Specifies the name of a jpeg file to be dumped at the same time of the ascii file, as a jpeg rendering of the last grabbed frame. By default this option is deactivated (unuseful when in \fBlive\fP mode).
.B
.IP "-Q --jpgqual"
Specifies the quality of the jpeg rendering.
.SH EXAMPLES
.B hasciicam -m html -o watchme.html
.br
puts your \fIhtml\fP formatted ascii into watchme.html
.br
.B hasciicam -m text -s79x24 -o ~/.plan
.br
puts your ascii into your local .plan (fingercam)
.SH NOTES
When using a usb webcam, a supported size needs to be specified. The minimum or maximum detected size should work, also a size of 160x120 mostly gives good results, with unsupported sizes you will get unexpected results.
.SH BUGS
Report bugs to hasciicam@dyne.org. Please include a complete, self-contained example that will allow the bug to be reproduced, informations about which version of hasciicam you are using, which operative system and the complete device detection output.
.SH AUTHOR
jaromil [aka Denis Roio] <\fIjaromil@dyne.org\fR>
.SH COPYING
Copyright (c) 2001 jaromil@dyne.org
.br
Permission is granted to copy, distribute and/or modify this manual under the terms of the GNU Free Documentation License, Version 1.1 or any later version published by the Free Software Foundation; with the Invariant Sections being NAME, SYNOPSIS, DESCRIPTION, AUTHOR and with the Front-Cover Texts including "hasciicam - (h)ascii for the masses! - manual pages". Permission is granted to make and distribute verbatim copies of this manual page provided the above copyright notice and this permission notice are preserved on all copies.
.SH AVAILABILITY
The most recent version of hasciicam sourcecode is always available for download from \fIhttp://ascii.dyne.org\fR.
.SH SEE ALSO
info aalib
